// <auto-generated />
namespace LTQL_1721050229.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ltql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ltql));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210613468_ltql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
